### ISSUE TITLE
wrap everything around

### ISSUE THREAD

**Issue by MariaTsantaki** [MariaTsantaki/spectroscopy-ML#4]
Now we are testing separately the method. It is time to wrap everything in one code.

**Comment by DanielAndreasen** [comment]
Yes! Very good point. Should we decide a path to follow? Obviously I like my own code (since it is small, simple, and easy to read) :P
Also it should be quite easy to extend. One thing is in the [`Data` class](https://github.com/MariaTsantaki/spectroscopy-ML/blob/master/model_training.py#L10-L52) to include more methods. The same with some of the other classes.

**Comment by MariaTsantaki** [comment]
I added the spectroscopy_ml file for testing
